spring:
  application:
    name: SystemCallAndTask

  datasource:
    url: jdbc:mysql://localhost:3306/call_dev_v1_1?useSSL=false&serverTimezone=UTC
    username: root
    password: masterkey
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: MySQL8Dialect

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath=db/migration


sso:
  base-endpoint: ${SSO_BASE_ENDPOINT:http://localhost:3000}
  check-token-endpoint: ${SSO_CHECK_TOKEN_ENDPOINT:/auth/check_token}
app:
  security:
    public-endpoints: $PUBLIC_ENDPOINTS:/online}