INSERT INTO STATUS (NAME_STATUS) VALUES ('Pendente');
INSERT INTO STATUS (NAME_STATUS) VALUES ('Recusado');
INSERT INTO STATUS (NAME_STATUS) VALUES ('Atribuido');
INSERT INTO STATUS (NAME_STATUS) VALUES ('Em Andamento');
INSERT INTO STATUS (NAME_STATUS) VALUES ('Aguardando retorno');
INSERT INTO STATUS (NAME_STATUS) VALUES ('Transferido');
INSERT INTO STATUS (NAME_STATUS) VALUES ('Resolvido');
INSERT INTO STATUS (NAME_STATUS) VALUES ('Fechado');