INSERT INTO SECTOR (NAME_SECTOR) VALUES ('Gerente');
INSERT INTO SECTOR (NAME_SECTOR) VALUES ('Supervisor');
INSERT INTO SECTOR (NAME_SECTOR) VALUES ('Financeiro');
INSERT INTO SECTOR (NAME_SECTOR) VALUES ('Faturamento');
INSERT INTO SECTOR (NAME_SECTOR) VALUES ('Eccomerce');
INSERT INTO SECTOR (NAME_SECTOR) VALUES ('TI');
INSERT INTO SECTOR (NAME_SECTOR) VALUES ('Vendedor');