INSERT INTO SOFTWARE (NAME_SOFTWARE) VALUES ('Sinergia 1.0');
INSERT INTO SOFTWARE (NAME_SOFTWARE) VALUES ('Sinergia 2.0');
INSERT INTO SOFTWARE (NAME_SOFTWARE) VALUES ('Ion Vendas');
INSERT INTO SOFTWARE (NAME_SOFTWARE) VALUES ('Ion Supervisor');
INSERT INTO SOFTWARE (NAME_SOFTWARE) VALUES ('Ion Rotas');
INSERT INTO SOFTWARE (NAME_SOFTWARE) VALUES ('Winthor');
INSERT INTO SOFTWARE (NAME_SOFTWARE) VALUES ('ChatBot');
INSERT INTO SOFTWARE (NAME_SOFTWARE) VALUES ('Sistema de chamado');